workaround for mysql, jupyterhub stop working if mysql accently stop
set_default_headers() is called too earlier, and if no db connection, following exception occur
and no way to rollback

[E 2016-04-21 09:32:05.100 JupyterHub http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/tornado/web.py", line 2004, in execute
        **self.handler_kwargs)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/tornado/web.py", line 183, in __init__
        self.clear()
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/tornado/web.py", line 287, in clear
        self.set_default_headers()
      File "/home/server/jupyterhub/jupyterhub/handlers/base.py", line 102, in set_default_headers
        headers.setdefault("Content-Security-Policy", self.content_security_policy)
      File "/home/server/jupyterhub/jupyterhub/handlers/base.py", line 92, in content_security_policy
        "report-uri " + self.csp_report_uri,
      File "/home/server/jupyterhub/jupyterhub/handlers/base.py", line 81, in csp_report_uri
        url_path_join(self.hub.server.base_url, 'security/csp-report')
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
        return self.impl.get(instance_state(instance), dict_)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 578, in get
        value = self.callable_(state, passive)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 511, in _load_for_state
        passive
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 547, in _get_ident_for_use_get
        for pk in self.mapper.primary_key
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/strategies.py", line 547, in <listcomp>
        for pk in self.mapper.primary_key
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/mapper.py", line 2455, in _get_state_attr_by_column
        return state.manager[prop.key].impl.get(state, dict_, passive=passive)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 573, in get
        value = state._load_expired(state, passive)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 480, in _load_expired
        self.manager.deferred_scalar_loader(self, toload)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 664, in load_scalar_attributes
        only_load_props=attribute_names)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 219, in load_on_ident
        return q.one()
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2473, in one
        ret = list(self)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
        return self._execute_and_instances(context)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
        result = conn.execute(querycontext.statement, self._params)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1078, in _execute_context
        None, None)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
        exc_info
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
        raise value.with_traceback(tb)
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1071, in _execute_context
        conn = self._revalidate_connection()
      File "/home/server/y/envs/jupyter/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 391, in _revalidate_connection
        "Can't reconnect until invalid "
    sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT hubs.id AS hubs_id, hubs._server_id AS hubs__server_id \nFROM hubs \nWHERE hubs.id = %s'] [parameters: [{'%(139752624327984 param)s': 1}]]